"use client";

import { useState } from "react";
import { Alert, Box, Button, Chip, Container, MenuItem, Paper, Select, TextField, Typography } from "@mui/material";
import { deactivateStaff, inviteReviewer } from "@/app/admin/hodnotitelia/actions";
import type { AdminReviewer } from "@/components/admin-dashboard";

export function ReviewerAdmin({ reviewers }: { reviewers: AdminReviewer[] }) {
  const [error, setError] = useState("");
  return <Container maxWidth="md" sx={{ py: 4 }}><Typography variant="h4" gutterBottom>Správa používateľov</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Pozývaj hodnotiteľov alebo ďalších adminov a spravuj ich prístup.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Paper sx={{ p: 3, mb: 3, borderRadius: 3 }}><Typography variant="h6" gutterBottom>Nová pozvánka</Typography><Box component="form" action={async (formData) => { try { const result = await inviteReviewer(formData); setError(result.error || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Pozvanie zlyhalo"); } }} sx={{ display: "grid", gap: 2 }}><TextField label="Meno" name="displayName" required /><TextField label="E-mail" name="email" type="email" required /><Select name="role" defaultValue="reviewer"><MenuItem value="reviewer">Hodnotiteľ</MenuItem><MenuItem value="admin">Admin</MenuItem></Select><Button type="submit" variant="contained">Poslať pozvánku</Button></Box></Paper>{reviewers.map((reviewer) => <Paper key={reviewer.id} sx={{ p: 2, mb: 1, borderRadius: 2, opacity: reviewer.is_active ? 1 : .6 }}><Box sx={{ display: "flex", alignItems: "center", gap: 1, flexWrap: "wrap" }}><Typography sx={{ fontWeight: 700 }}>{reviewer.display_name || reviewer.email}</Typography><Chip size="small" label={reviewer.role === "admin" ? "Admin" : "Hodnotiteľ"} color={reviewer.role === "admin" ? "secondary" : "primary"} /><Chip size="small" label={reviewer.is_active ? "Aktívny" : "Deaktivovaný"} color={reviewer.is_active ? "success" : "default"} /></Box><Typography variant="body2" color="text.secondary">{reviewer.email} · čaká: {reviewer.pending_count} · hotovo: {reviewer.completed_count}</Typography>{reviewer.is_active && <Box component="form" action={async (formData) => { const result = await deactivateStaff(formData); setError(result.error || ""); }} sx={{ mt: 1 }}><input type="hidden" name="profileId" value={reviewer.id} /><Button type="submit" size="small" color="error">Deaktivovať prístup</Button></Box>}</Paper>)}</Container>;
}
